/**
 * Mock Data for Grace International HRM System
 * This file contains comprehensive mock data for all API endpoints
 */

export const mockEmployees = [
  {
    id: 1,
    name: "Raj Kumar",
    email: "raj.kumar@graceinternational.com",
    employeeId: "GI-001",
    phone: "9841234567",
    department: "Management",
    role: "HR Manager",
    branch: "Kathmandu",
    joinDate: "2022-01-15",
    createdAt: "2022-01-15T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/raj-kumar.jpg",
  },
  {
    id: 2,
    name: "Priya Sharma",
    email: "priya.sharma@graceinternational.com",
    employeeId: "GI-002",
    phone: "9842345678",
    department: "Operations",
    role: "Operations Officer",
    branch: "Kathmandu",
    joinDate: "2022-03-20",
    createdAt: "2022-03-20T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/priya-sharma.jpg",
  },
  {
    id: 3,
    name: "Amit Patel",
    email: "amit.patel@graceinternational.com",
    employeeId: "GI-003",
    phone: "9843456789",
    department: "Education",
    role: "Program Coordinator",
    branch: "Butwal",
    joinDate: "2022-05-10",
    createdAt: "2022-05-10T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/amit-patel.jpg",
  },
  {
    id: 4,
    name: "Neha Verma",
    email: "neha.verma@graceinternational.com",
    employeeId: "GI-004",
    phone: "9844567890",
    department: "Migration Services",
    role: "Migration Counselor",
    branch: "Pokhara",
    joinDate: "2022-06-15",
    createdAt: "2022-06-15T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/neha-verma.jpg",
  },
  {
    id: 5,
    name: "Suresh Nair",
    email: "suresh.nair@graceinternational.com",
    employeeId: "GI-005",
    phone: "9845678901",
    department: "IT",
    role: "System Administrator",
    branch: "Kathmandu",
    joinDate: "2022-02-01",
    createdAt: "2022-02-01T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/suresh-nair.jpg",
  },
  {
    id: 6,
    name: "Kavya Singh",
    email: "kavya.singh@graceinternational.com",
    employeeId: "GI-006",
    phone: "9846789012",
    department: "Finance",
    role: "Finance Officer",
    branch: "Kathmandu",
    joinDate: "2022-04-05",
    createdAt: "2022-04-05T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/kavya-singh.jpg",
  },
  {
    id: 7,
    name: "Rohan Das",
    email: "rohan.das@graceinternational.com",
    employeeId: "GI-007",
    phone: "9847890123",
    department: "Education",
    role: "Curriculum Developer",
    branch: "Nepalgunj",
    joinDate: "2022-07-20",
    createdAt: "2022-07-20T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/rohan-das.jpg",
  },
  {
    id: 8,
    name: "Mausam Kunwar",
    email: "mausam@graceinternational.com",
    employeeId: "GI-ADMIN-001",
    phone: "9840000000",
    department: "Administration",
    role: "CEO",
    branch: "Kathmandu",
    joinDate: "2020-01-01",
    createdAt: "2020-01-01T08:00:00Z",
    status: "active",
    photo: "/uploads/employees/mausam.jpg",
  },
];

export const mockAttendance = [
  {
    id: 1,
    employeeId: 1,
    employee: mockEmployees[0],
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    checkInTime: "09:00:00",
    checkOutTime: "17:30:00",
    status: "present",
    duration: 8.5,
  },
  {
    id: 2,
    employeeId: 2,
    employee: mockEmployees[1],
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    checkInTime: "08:45:00",
    checkOutTime: "17:15:00",
    status: "present",
    duration: 8.5,
  },
  {
    id: 3,
    employeeId: 3,
    employee: mockEmployees[2],
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    checkInTime: null,
    checkOutTime: null,
    status: "absent",
    duration: 0,
  },
  {
    id: 4,
    employeeId: 1,
    employee: mockEmployees[0],
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    checkInTime: "09:15:00",
    checkOutTime: "17:45:00",
    status: "present",
    duration: 8.5,
  },
  {
    id: 5,
    employeeId: 2,
    employee: mockEmployees[1],
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    checkInTime: "09:00:00",
    checkOutTime: "17:30:00",
    status: "present",
    duration: 8.5,
  },
  {
    id: 6,
    employeeId: 4,
    employee: mockEmployees[3],
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    checkInTime: "09:30:00",
    checkOutTime: "16:45:00",
    status: "present",
    duration: 7.25,
  },
  {
    id: 7,
    employeeId: 1,
    employee: mockEmployees[0],
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    checkInTime: "09:05:00",
    checkOutTime: null,
    status: "present",
    duration: null,
  },
];

export const mockLeaveRequests = [
  {
    id: 1,
    employeeId: 1,
    employee: mockEmployees[0],
    leaveType: "Annual",
    fromDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    toDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    days: 5,
    reason: "Personal vacation",
    status: "approved",
    approvedBy: "Raj Kumar",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    employeeId: 2,
    employee: mockEmployees[1],
    leaveType: "Sick",
    fromDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    toDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    days: 2,
    reason: "Medical appointment",
    status: "pending",
    approvedBy: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    employeeId: 4,
    employee: mockEmployees[3],
    leaveType: "Annual",
    fromDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    toDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    days: 4,
    reason: "Family vacation",
    status: "approved",
    approvedBy: "Raj Kumar",
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    employeeId: 3,
    employee: mockEmployees[2],
    leaveType: "Casual",
    fromDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    toDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    days: 1,
    reason: "Personal work",
    status: "rejected",
    approvedBy: "Raj Kumar",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockNotices = [
  {
    id: 1,
    title: "Welcome to Grace International HR Portal",
    content:
      "Welcome to our comprehensive HR Management System. This system helps manage employees, attendance, leave requests, and company notices efficiently.",
    type: "General",
    isActive: true,
    priority: 1,
    author: "System",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    photo: null,
  },
  {
    id: 2,
    title: "Office Closure - National Holiday",
    content:
      "The office will remain closed on June 15, 2025 (Rato Machhindranath Jatra). All employees should plan their work accordingly.",
    type: "Announcement",
    isActive: true,
    priority: 2,
    author: "Administration",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    photo: null,
  },
  {
    id: 3,
    title: "Updated Leave Policy",
    content:
      "Please review the updated leave policy effective from July 1, 2025. Employees are entitled to 20 days of annual leave. For details, contact HR.",
    type: "Policy",
    isActive: true,
    priority: 2,
    author: "HR Team",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    photo: null,
  },
  {
    id: 4,
    title: "Team Building Event",
    content:
      "We are organizing a team building event on June 28, 2025 at the company grounds. All employees are welcome to participate. Refreshments will be provided.",
    type: "Event",
    isActive: true,
    priority: 3,
    author: "Events Team",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    photo: null,
  },
  {
    id: 5,
    title: "System Maintenance Notice",
    content:
      "The HR portal will undergo scheduled maintenance on June 20, 2025 from 11:00 PM to 2:00 AM. Services will be temporarily unavailable during this period.",
    type: "General",
    isActive: false,
    priority: 1,
    author: "IT Department",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    photo: null,
  },
];

export const mockHolidays = [
  {
    id: 1,
    name: "Rato Machhindranath Jatra",
    date: "2025-06-15",
    type: "National",
    description: "Important cultural festival",
  },
  {
    id: 2,
    name: "Janai Purnima",
    date: "2025-07-29",
    type: "National",
    description: "Festival celebration",
  },
  {
    id: 3,
    name: "Krishna Janmashtami",
    date: "2025-08-19",
    type: "National",
    description: "Hindu festival",
  },
  {
    id: 4,
    name: "Gai Jatra",
    date: "2025-08-21",
    type: "National",
    description: "Festival of lights",
  },
  {
    id: 5,
    name: "Dashain (Vijaya Dashami)",
    date: "2025-10-11",
    type: "National",
    description: "Major festival",
  },
  {
    id: 6,
    name: "Tihar",
    date: "2025-10-29",
    type: "National",
    description: "Festival of lights",
  },
  {
    id: 7,
    name: "Govardhan Puja",
    date: "2025-10-30",
    type: "National",
    description: "Hindu festival",
  },
];

export const mockGlobalSettings = {
  id: 1,
  companyName: "Grace International",
  companyEmail: "info@graceinternational.com",
  companyPhone: "+977-1-4123456",
  companyAddress: "Kathmandu, Nepal",
  website: "www.graceinternational.com",
  officeStartTime: "09:00",
  officeEndTime: "17:30",
  workingDays: [1, 2, 3, 4, 5],
  timezone: "Asia/Kathmandu",
  currency: "NPR",
  dateFormat: "YYYY-MM-DD",
};

export const mockPopups = {
  id: 1,
  title: "Announcement",
  type: "mixed",
  textContent: "Welcome to Grace International!",
  isActive: true,
  displayDuration: 5000,
};

export const mockIpSettings = [
  {
    id: 1,
    branch: "Kathmandu",
    allowedIpAddress: "192.168.1.0",
    isActive: true,
    allowedIps: ["192.168.1.100", "192.168.1.101", "192.168.1.102"],
  },
  {
    id: 2,
    branch: "Butwal",
    allowedIpAddress: "192.168.2.0",
    isActive: true,
    allowedIps: ["192.168.2.100", "192.168.2.101"],
  },
  {
    id: 3,
    branch: "Pokhara",
    allowedIpAddress: "192.168.3.0",
    isActive: true,
    allowedIps: ["192.168.3.100"],
  },
  {
    id: 4,
    branch: "Nepalgunj",
    allowedIpAddress: "192.168.4.0",
    isActive: false,
    allowedIps: ["192.168.4.100"],
  },
];

export const mockBranchNetwork = [
  {
    id: 1,
    branch: "Kathmandu",
    allowedIpAddress: "192.168.1.0/24",
    isActive: true,
  },
  {
    id: 2,
    branch: "Butwal",
    allowedIpAddress: "192.168.2.0/24",
    isActive: true,
  },
  {
    id: 3,
    branch: "Pokhara",
    allowedIpAddress: "192.168.3.0/24",
    isActive: true,
  },
  {
    id: 4,
    branch: "Nepalgunj",
    allowedIpAddress: "192.168.4.0/24",
    isActive: false,
  },
];

export const mockAuth = {
  user: {
    id: 1,
    name: "Mausam Kunwar",
    email: "mausam@graceinternational.com",
    role: "superadmin",
    branch: "Kathmandu",
  },
  token: "mock-jwt-token-12345",
  refreshToken: "mock-refresh-token-67890",
};

export const mockLoginResponse = {
  accessToken: "mock-access-token",
  user: {
    id: 1,
    username: "mausam",
    role: "superadmin",
    branch: "Kathmandu",
  },
};

// Utility function to simulate network delay
export const delay = (ms = 300) => new Promise((resolve) => setTimeout(resolve, ms));

// Utility function to simulate random success/failure for certain operations
export const shouldFail = (probability = 0.1) => Math.random() < probability;
